/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import model.Mesto;

/**
 *
 * @author Korisnik
 */
public class MestoKreirajForma extends javax.swing.JDialog {

    private MestoForma roditelj;
    private Mesto mesto;

    /**
     * Creates new form MestoKreirajForma
     */
    public MestoKreirajForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        roditelj = (MestoForma) parent;
        popuniFormuKreiraj();
    }

    public MestoKreirajForma(java.awt.Frame parent, boolean modal, Mesto mesto) {
        super(parent, modal);
        initComponents();
        roditelj = (MestoForma) parent;
        this.mesto = mesto;
        popuniFormuDetalji();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPostanski = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonKreiraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Naziv");

        jLabel1.setText("Postanski broj");

        jLabel3.setText("Podaci");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPostanski)
                            .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPostanski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonKreiraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonIzmeni)
                .addGap(18, 18, 18)
                .addComponent(jButtonSacuvaj)
                .addGap(18, 18, 18)
                .addComponent(jButtonObrisi)
                .addGap(18, 18, 18)
                .addComponent(jButtonKreiraj)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
//        String id = jTextFieldPostanski.getText();
//        String naziv = jTextFieldNaziv.getText();
//
//        if (!validacija(id, naziv)) {
//            JOptionPane.showMessageDialog(this, "Proverite unesete podatke", "Greska", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        Mesto mesto = new Mesto(id, naziv, false);
//        boolean uspesno = Controller.getInstance().kreirajMesto(mesto);
//        if (uspesno) {
//            roditelj.popuniTabelu();
//            JOptionPane.showMessageDialog(this, "Mesto je uspesno ubaceno u bazu", "Obaveztenje", JOptionPane.INFORMATION_MESSAGE);
//            this.dispose();
//        } else {
//            JOptionPane.showMessageDialog(this, "Greska pri unosu mesta u bazu", "Greska", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        jTextFieldNaziv.setEnabled(true);
        jButtonSacuvaj.setEnabled(true);
        jButtonObrisi.setEnabled(false);
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed

        int odgovor = JOptionPane.showConfirmDialog(this, "Da li zelite da obrisete mesto?", "Potvrda", JOptionPane.YES_NO_OPTION);
        if (odgovor != JOptionPane.YES_OPTION) {
            return;
        }

        obrisiMesto(mesto);
        this.dispose();
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
//        String id = jTextFieldPostanski.getText();
//        String naziv = jTextFieldNaziv.getText();
//
//        if (!validacija(id, naziv)) {
//            JOptionPane.showMessageDialog(this, "Proverite unesete podatke", "Greska", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//        Mesto mesto = new Mesto(id, naziv, false);
//        boolean uspesno = Controller.getInstance().promeniMesto(mesto);
//        if (uspesno) {
//            roditelj.popuniTabelu();
//            JOptionPane.showMessageDialog(this, "Mesto je uspesno promenjeno", "Obaveztenje", JOptionPane.INFORMATION_MESSAGE);
//            this.dispose();
//        } else {
//            JOptionPane.showMessageDialog(this, "Greska pri promeni mesta", "Greska", JOptionPane.ERROR_MESSAGE);
//        }
//        
//        
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MestoKreirajForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MestoKreirajForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MestoKreirajForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MestoKreirajForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MestoKreirajForma dialog = new MestoKreirajForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldPostanski;
    // End of variables declaration//GEN-END:variables

    private boolean validacija(String id, String naziv) {
        boolean idReg = id.matches("^\\d{5}$");
        boolean nazivReg = naziv.matches("^[A-Z][a-zA-Z ]*$");

        if (idReg && nazivReg) {
            return true;
        }

        if (!idReg) {
            jTextFieldPostanski.setBorder(new LineBorder(Color.RED, 3));
        }
        if (!nazivReg) {
            jTextFieldNaziv.setBorder(new LineBorder(Color.RED, 3));
        }

        JOptionPane.showMessageDialog(this, "Greska prilikom unosa podataka", "Greska", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    private void popuniFormuKreiraj() {
        jButtonIzmeni.setVisible(false);
        jButtonObrisi.setVisible(false);
        jButtonSacuvaj.setVisible(false);
    }

    private void popuniFormuDetalji() {
        jButtonKreiraj.setVisible(false);
        jTextFieldPostanski.setEnabled(false);
        jTextFieldNaziv.setEnabled(false);
        jTextFieldPostanski.setText(mesto.getPostanskiBroj());
        jTextFieldNaziv.setText(mesto.getNazivMesto());
        jButtonSacuvaj.setEnabled(false);

    }

    public void obrisiMesto(Mesto mesto) {

        if (obrisiIzBaze(mesto)) {
            roditelj.popuniTabelu();

        }
    }

    private boolean obrisiIzBaze(Mesto mesto) {
//        mesto.setObrisano(true);
//        boolean uspesno = Controller.getInstance().obrisiMesto(mesto);
//        if (uspesno) {
//            JOptionPane.showMessageDialog(this, "Mesto je obrisano iz baze", "Obavestenje", JOptionPane.INFORMATION_MESSAGE);
//            return true;
//        } else {
//            JOptionPane.showMessageDialog(this, "Mesto nije obrisano iz baze", "Greska", JOptionPane.ERROR_MESSAGE);
//            return false;
//        }
//    }
        return true;
    }
}
