/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import condinator.Cordinator;
import java.awt.event.ActionListener;
import java.lang.ModuleLayer.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Sponzor;
import model.Menadzer;
import model.Projekat;
import modeliTabela.ProjekatModelTabele;

/**
 *
 * @author Korisnik
 */
public class ProjektiForma extends javax.swing.JFrame {

    private Sponzor sponzor = null;
    private Menadzer men;

    public Sponzor getSponzor() {
        return sponzor;
    }

    /**
     * Creates new form ProjektiForma
     */
    public ProjektiForma() {
        initComponents();

        setTitle("Projekti");

        popuniComboBox();
        setDefaultCloseOperation(ProjektiForma.DISPOSE_ON_CLOSE);
    }

    public JComboBox<Sponzor> getjComboBoxSponzor() {
        return jComboBoxSponzor;
    }

    public void setjComboBoxSponzor(JComboBox<Sponzor> jComboBoxIzvodjac) {
        this.jComboBoxSponzor = jComboBoxIzvodjac;
    }

    public JComboBox<Menadzer> getjComboBoxMenadzer() {
        return jComboBoxMenadzer;
    }

    public void setjComboBoxMenadzer(JComboBox<Menadzer> jComboBoxMenadzer) {
        this.jComboBoxMenadzer = jComboBoxMenadzer;
    }

    public JTable getjTableProjekti() {
        return jTableProjekti;
    }

    public void setjTableProjekti(JTable jTableProjekti) {
        this.jTableProjekti = jTableProjekti;
    }

    public ProjektiForma(Sponzor sponzor) {
        initComponents();

        setTitle("Projekti");

        popuniComboBox();
        setDefaultCloseOperation(ProjektiForma.DISPOSE_ON_CLOSE);
        popuniFiltrirano(sponzor);

        this.sponzor = sponzor;
        setDefaultCloseOperation(MenadzerNalogForma.DISPOSE_ON_CLOSE);

    }

    public ProjektiForma(Menadzer men) {
        initComponents();

        setTitle("Projekti");
        popuniComboBox();
        this.men = men;
        popuniFiltrirano(men);

        setDefaultCloseOperation(ProjektiForma.DISPOSE_ON_CLOSE);
    }

    public Menadzer getMen() {
        return men;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldRegBroj = new javax.swing.JTextField();
        jComboBoxMenadzer = new javax.swing.JComboBox<>();
        jComboBoxSponzor = new javax.swing.JComboBox<>();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonOcistiFilter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjekti = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonDetalji = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Kriterijumi pretrage");

        jLabel2.setText("Reg broj");

        jLabel3.setText("Menadzer");

        jLabel4.setText("Sponzor");

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonOcistiFilter.setText("Ocisti filter");
        jButtonOcistiFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcistiFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxSponzor, 0, 189, Short.MAX_VALUE)
                                    .addComponent(jComboBoxMenadzer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(128, 128, 128)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonOcistiFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldRegBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldRegBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxSponzor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonOcistiFilter)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTableProjekti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProjekti);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        jButtonDetalji.setText("Detalji");
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonDetalji)
                    .addComponent(jButtonKreiraj))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButtonKreiraj)
                .addGap(45, 45, 45)
                .addComponent(jButtonDetalji)
                .addGap(52, 52, 52)
                .addComponent(jButtonNazad)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        Cordinator.getInstance().otvoriProjektiKreirajFormu(this, null);
    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
//        int sel = jTableProjekti.getSelectedRow();
//
//        if (sel == -1) {
//            JOptionPane.showMessageDialog(this, "Odaberite projektni ugovor", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
//            return;
//        }
//        
//        ProjekatModelTabele pmt=(ProjekatModelTabele) jTableProjekti.getModel();
//        
//        Projekat pu = pmt.getLista().get(sel);
//
//        ProjektiKreirajForma kpf = new ProjektiKreirajForma(this, true, pu);
//        kpf.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_jButtonDetaljiActionPerformed

    public JTextField getjTextFieldRegBroj() {
        return jTextFieldRegBroj;
    }

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed

//        String regBroj = jTextField1.getText();
//        Menadzer menadzer = (Menadzer) jComboBoxMenadzer.getSelectedItem();
//        Sponzor izvodjac = (Sponzor) jComboBoxIzvodjac.getSelectedItem();
//        VrstaAktivnosti vakt = (VrstaAktivnosti) jComboBoxVAktivnosti.getSelectedItem();
//
//        if (!regBroj.isEmpty() && !regBroj.matches("\\d{4}/20\\d{2}")) {
//            JOptionPane.showMessageDialog(this, "Proverite unesene podatke", "Greska", JOptionPane.ERROR_MESSAGE);
//            jTextField1.setBorder(new LineBorder(Color.RED, 3));
//            return;
//        }
//        List<Projekat> listaUgovora = new ArrayList<>();
//
//        Projekat ugovor = new Projekat();
//        ugovor.setRegBroj("");
//
//        ProjekatModelTabele pmt = null;
//
//        boolean kriterijumUgovor = false;
//        boolean kriterijumIzvodjac = false;
//        boolean kriterijumMenadzer = false;
//        boolean kriterijumVakt = false;
//
//        if (!regBroj.isEmpty()) {
//            ugovor.setRegBroj(regBroj);
//            kriterijumUgovor = Controller.getInstance().vratiListuProjektniUgovor(ugovor, listaUgovora);
//
//        }
//        if (izvodjac != null) {
//            kriterijumIzvodjac = Controller.getInstance().vratiListuProjektniUgovor(izvodjac, listaUgovora);
//        }
//        if (menadzer != null) {
//            kriterijumMenadzer = Controller.getInstance().vratiListuProjektniUgovor(menadzer, listaUgovora);
//        }
//        if (vakt != null) {
//            kriterijumVakt = Controller.getInstance().vratiListuProjektniUgovor(vakt, listaUgovora);
//        }
//
//        if (kriterijumMenadzer || kriterijumIzvodjac || kriterijumVakt || kriterijumUgovor) {
//
//            pmt = new ProjekatModelTabele(listaUgovora);
//
//            jTableProjekti.setModel(pmt);
//
//        } else {
//            JOptionPane.showMessageDialog(this, "Sistem ne moze da pronadje ugovor o radu");
//
//        }

    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    private void jButtonOcistiFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcistiFilterActionPerformed
//        jTextFieldRegBroj.setText("");
//        jComboBoxSponzor.setSelectedItem(null);
//        jComboBoxMenadzer.setSelectedItem(null);
//        
//        popuniTabelu();
    }//GEN-LAST:event_jButtonOcistiFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjektiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjektiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjektiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjektiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjektiForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonOcistiFilter;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JComboBox<Menadzer> jComboBoxMenadzer;
    private javax.swing.JComboBox<model.Sponzor> jComboBoxSponzor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableProjekti;
    private javax.swing.JTextField jTextFieldRegBroj;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
//        List<Menadzer> listaMen = new ArrayList<>();
//        boolean uspesnoM = Controller.getInstance().vratiListuSviMenadzer(listaMen);
//        if (uspesnoM) {
//            for (Menadzer men : listaMen) {
//                jComboBoxMenadzer.addItem(men);
//            }
//            jComboBoxMenadzer.setSelectedItem(null);
//        } else {
//            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita listu menadzera", "Greska", JOptionPane.ERROR_MESSAGE);
//        }
//
//        List<Sponzor> listaGI = new ArrayList<>();
//        boolean uspesnoI = Controller.getInstance().vratiListuSviSponzor(listaGI);
//        if (uspesnoI) {
//            for (Sponzor gi : listaGI) {
//                jComboBoxIzvodjac.addItem(gi);
//            }
//            jComboBoxIzvodjac.setSelectedItem(null);
//        } else {
//            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita listu izvodjaca", "Greska", JOptionPane.ERROR_MESSAGE);
//        }
//
//        List<VrstaAktivnosti> listaVA = new ArrayList<>();
//        boolean uspesnoVA = Controller.getInstance().vratiListuSviVrstaAktivnosti(listaVA);
//        if (uspesnoVA) {
//            for (VrstaAktivnosti va:listaVA  ) {
//                jComboBoxVAktivnosti.addItem(va);
//            }
//            jComboBoxVAktivnosti.setSelectedItem(null);
//        } else {
//            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita listu vrsta aktivnosti", "Greska", JOptionPane.ERROR_MESSAGE);
//        }
    }

    private void popuniFiltrirano(Menadzer men) {
        List<Projekat> lista = new ArrayList<>();
        boolean uspesno = komunikacijaKlijent.Komunikacija.getInstance().vratiListuProjektniUgovor(men, lista);
        if (uspesno) {
            ProjekatModelTabele pmt = new ProjekatModelTabele(lista);
            jTableProjekti.setModel(pmt);

        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita listu projektnih ugovora", "Greska", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }

    }

    private void popuniFiltrirano(Sponzor sponzor) {
        List<Projekat> lista = new ArrayList<>();
        boolean uspesno = komunikacijaKlijent.Komunikacija.getInstance().vratiListuProjektniUgovor(sponzor, lista);
        if (uspesno) {
            ProjekatModelTabele pmt = new ProjekatModelTabele(lista);
            jTableProjekti.setModel(pmt);

        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita listu projektnih ugovora", "Greska", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void pretraziActionListener(ActionListener actionListener) {
        jButtonPretrazi.addActionListener(actionListener);
    }

    public void ocitstiActionListener(ActionListener actionListener) {
        jButtonOcistiFilter.addActionListener(actionListener);
    }

    public void detaljiActionListener(ActionListener actionListener) {
        jButtonDetalji.addActionListener(actionListener);
    }
}
