/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import condinator.Cordinator;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import language.LanguageManager;
import model.Aktivnost;
import model.JeSponzor;
import model.Sponzor;
import model.Menadzer;
import model.Projekat;
import model.VrstaAktivnosti;
import modeliTabela.AktivnostModelTabele;
import modeliTabela.JeSponzorModelTabele;

/**
 *
 * @author Korisnik
 */
public class ProjektiKreirajForma extends javax.swing.JDialog {

    private Projekat pu = new Projekat();
    boolean kreiranje = false;
    private ProjektiForma roditelj;
    private int brojAkt = 0;
    private Sponzor gi;

    /**
     * Creates new form ProjektiKreirajForma
     */
    public ProjektiKreirajForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension velicinaEkrana = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(velicinaEkrana.width, velicinaEkrana.height);
        setLabels();
        setResizable(true);
        setTitle(LanguageManager.getString("create_project_title"));
        roditelj = (ProjektiForma) parent;
        popuniComboBox();
        popuniTabeluKreiraj();
        pripremiFormuKreiraj();

    }

    public ProjektiKreirajForma(java.awt.Frame parent, boolean modal, Projekat pu) {
        super(parent, modal);
        initComponents();
        Dimension velicinaEkrana = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(velicinaEkrana.width, velicinaEkrana.height);
        setLabels();
        setResizable(true);
      
        roditelj = (ProjektiForma) parent;
        this.pu = pu;
        popuniComboBox();
        popuniTabeluDetalji();
        kreiranje = false;
        popuniFormuDetalji();
        setTitle(LanguageManager.getString("update_project_title"));
        setDefaultCloseOperation(ProjektiKreirajForma.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPodaciProj = new javax.swing.JLabel();
        jLabelRegBroj = new javax.swing.JLabel();
        jLabelOpisProj = new javax.swing.JLabel();
        jLabelDatPoc = new javax.swing.JLabel();
        jLabelDatZav = new javax.swing.JLabel();
        jLabelTrajanje = new javax.swing.JLabel();
        jLabelBudzet = new javax.swing.JLabel();
        jLabelMen = new javax.swing.JLabel();
        jTextFieldRegBr = new javax.swing.JTextField();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldOpisProjekta = new javax.swing.JTextField();
        jTextFielDatumOD = new javax.swing.JTextField();
        jTextFieldDatumDO = new javax.swing.JTextField();
        jTextFieldTrajanje = new javax.swing.JTextField();
        jTextFieldBudzet = new javax.swing.JTextField();
        jLabelNazivProj = new javax.swing.JLabel();
        jComboBoxMenadzer = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSponzori = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButtonObrisiSponzor = new javax.swing.JButton();
        jButtonDodajSponzor = new javax.swing.JButton();
        jComboBoxSponzor = new javax.swing.JComboBox<>();
        jLabelSpon = new javax.swing.JLabel();
        jCheckBoxRobni = new javax.swing.JCheckBox();
        jCheckBoxNovcani = new javax.swing.JCheckBox();
        jTextFieldIznosSponz = new javax.swing.JTextField();
        jLabelIznosSpon = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPodaciAkt = new javax.swing.JLabel();
        jLabelNazviAkt = new javax.swing.JLabel();
        jLabelOpisAkt = new javax.swing.JLabel();
        jLabelVrstaAkt = new javax.swing.JLabel();
        jTextFieldNazivAkt = new javax.swing.JTextField();
        jTextFieldOpisAkt = new javax.swing.JTextField();
        jComboBoxVAktivnosti = new javax.swing.JComboBox<>();
        jButtonDodajAkt = new javax.swing.JButton();
        jButtonObrisiAkt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAktivnost = new javax.swing.JTable();
        jButtonNazad = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1514, 155));

        jLabelPodaciProj.setText("Podaci o projektu");

        jLabelRegBroj.setText("Reg broj");

        jLabelOpisProj.setText("Opsi projekta");

        jLabelDatPoc.setText("Datum pocetka");

        jLabelDatZav.setText("Datum zavrsetka");

        jLabelTrajanje.setText("Trajanje [h]");

        jLabelBudzet.setText("Budzet [€]");

        jLabelMen.setText("Menadzer");

        jTextFielDatumOD.setText("dd-mm-yyyy");
        jTextFielDatumOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielDatumODActionPerformed(evt);
            }
        });

        jTextFieldDatumDO.setText("dd-mm-yyyy");

        jLabelNazivProj.setText("Naziv projekta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNazivProj, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRegBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRegBr, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDatPoc, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelOpisProj, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOpisProjekta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFielDatumOD, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelDatZav, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jTextFieldDatumDO, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelBudzet, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(jLabelMen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBudzet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxMenadzer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPodaciProj, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelPodaciProj)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegBroj)
                    .addComponent(jTextFieldRegBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBudzet)
                    .addComponent(jTextFieldBudzet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDatumDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDatZav)
                    .addComponent(jTextFieldOpisProjekta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOpisProj))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNazivProj)
                        .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDatPoc)
                        .addComponent(jTextFielDatumOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTrajanje))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMen)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(754, 411));

        jTableSponzori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableSponzori);

        jButtonObrisiSponzor.setText("Obrisi");
        jButtonObrisiSponzor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiSponzorActionPerformed(evt);
            }
        });

        jButtonDodajSponzor.setText("Dodaj");
        jButtonDodajSponzor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajSponzorActionPerformed(evt);
            }
        });

        jLabelSpon.setText("Sponzori");

        jCheckBoxRobni.setText("Robno sponzorstvo");

        jCheckBoxNovcani.setText("Novcano sponzorstvo");

        jLabelIznosSpon.setText("Iznos sponzorstva [€]");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabelSpon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jCheckBoxRobni, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelIznosSpon, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jComboBoxSponzor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jCheckBoxNovcani, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIznosSponz, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonObrisiSponzor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDodajSponzor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSpon)
                    .addComponent(jCheckBoxRobni)
                    .addComponent(jLabelIznosSpon)
                    .addComponent(jButtonDodajSponzor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxSponzor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBoxNovcani))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIznosSponz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonObrisiSponzor)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPodaciAkt.setText("Podaci o aktivnostima");

        jLabelNazviAkt.setText("Naziv aktivnosti");

        jLabelOpisAkt.setText("Opis ");

        jLabelVrstaAkt.setText("Vrsta");

        jButtonDodajAkt.setText("Dodaj");
        jButtonDodajAkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajAktActionPerformed(evt);
            }
        });

        jButtonObrisiAkt.setText("Obrisi aktivnost");
        jButtonObrisiAkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiAktActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNazviAkt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOpisAkt, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(jLabelVrstaAkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldOpisAkt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNazivAkt)
                                    .addComponent(jComboBoxVAktivnosti, 0, 223, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonDodajAkt)
                                        .addGap(114, 114, 114))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonObrisiAkt)
                                        .addGap(87, 87, 87))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelPodaciAkt)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelPodaciAkt)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodajAkt)
                    .addComponent(jLabelNazviAkt)
                    .addComponent(jTextFieldNazivAkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOpisAkt)
                    .addComponent(jTextFieldOpisAkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVrstaAkt)
                            .addComponent(jComboBoxVAktivnosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonObrisiAkt)
                        .addGap(35, 35, 35))))
        );

        jTableAktivnost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAktivnost);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Zavrsi sa kreiranjem");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(527, 527, 527)
                                .addComponent(jButtonNazad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButtonSacuvaj)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNazad)
                    .addComponent(jButtonSacuvaj))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed

        if (kreiranje) {
            sacuvajKreiranje();
        } else {
            sacuvajIzmene();
        }

    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonDodajAktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajAktActionPerformed

        String naziv = jTextFieldNazivAkt.getText();
        String opis = jTextFieldOpisAkt.getText();

        VrstaAktivnosti vakt = (VrstaAktivnosti) jComboBoxVAktivnosti.getSelectedItem();

        if (!validacijaAktivnosti(naziv, opis, vakt)) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("check_data"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }

        AktivnostModelTabele amt = (AktivnostModelTabele) jTableAktivnost.getModel();
        Aktivnost akt = new Aktivnost(pu, ++brojAkt, naziv, opis, false, vakt, null);
        amt.dodajElement(akt);
        azurirajRedneBrojeve();

    }//GEN-LAST:event_jButtonDodajAktActionPerformed

    private void jButtonObrisiAktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiAktActionPerformed
        int sel = jTableAktivnost.getSelectedRow();
        if (sel == -1) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("act_not_chosen"), LanguageManager.getString("warning"), JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        AktivnostModelTabele amt = (AktivnostModelTabele) jTableAktivnost.getModel();

        amt.ukloniElement(amt.getLista().get(sel));
        azurirajRedneBrojeve();

    }//GEN-LAST:event_jButtonObrisiAktActionPerformed

    private void jButtonDodajSponzorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajSponzorActionPerformed
        Sponzor sponzor = (Sponzor) jComboBoxSponzor.getSelectedItem();
        if (sponzor == null) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("spons_not_chosen"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean robni = false;
        boolean novcani = false;
        double iznos = 0;
        robni = jCheckBoxRobni.isSelected();
        novcani = jCheckBoxNovcani.isSelected();
        if (!robni && !novcani) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("spons_type_error"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!jTextFieldIznosSponz.getText().matches("\\d+(\\.\\d+)?")) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("amount_error"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        iznos = Double.parseDouble(jTextFieldIznosSponz.getText());

        JeSponzor js = new JeSponzor(pu, sponzor, robni, novcani, iznos);

        JeSponzorModelTabele smt = (JeSponzorModelTabele) jTableSponzori.getModel();
        smt.dodajElement(js);


    }//GEN-LAST:event_jButtonDodajSponzorActionPerformed

    private void jButtonObrisiSponzorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiSponzorActionPerformed

        int selektovan = jTableSponzori.getSelectedRow();
        if (selektovan == -1) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("spons_not_chosen"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }

        JeSponzorModelTabele smt = (JeSponzorModelTabele) jTableSponzori.getModel();

        smt.ukloniElement(selektovan);

    }//GEN-LAST:event_jButtonObrisiSponzorActionPerformed

    private void jTextFielDatumODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielDatumODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielDatumODActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ProjektiKreirajForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ProjektiKreirajForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ProjektiKreirajForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ProjektiKreirajForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ProjektiKreirajForma dialog = new ProjektiKreirajForma(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajAkt;
    private javax.swing.JButton jButtonDodajSponzor;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonObrisiAkt;
    private javax.swing.JButton jButtonObrisiSponzor;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JCheckBox jCheckBoxNovcani;
    private javax.swing.JCheckBox jCheckBoxRobni;
    private javax.swing.JComboBox<Menadzer> jComboBoxMenadzer;
    private javax.swing.JComboBox<model.Sponzor> jComboBoxSponzor;
    private javax.swing.JComboBox<VrstaAktivnosti> jComboBoxVAktivnosti;
    private javax.swing.JLabel jLabelBudzet;
    private javax.swing.JLabel jLabelDatPoc;
    private javax.swing.JLabel jLabelDatZav;
    private javax.swing.JLabel jLabelIznosSpon;
    private javax.swing.JLabel jLabelMen;
    private javax.swing.JLabel jLabelNazivProj;
    private javax.swing.JLabel jLabelNazviAkt;
    private javax.swing.JLabel jLabelOpisAkt;
    private javax.swing.JLabel jLabelOpisProj;
    private javax.swing.JLabel jLabelPodaciAkt;
    private javax.swing.JLabel jLabelPodaciProj;
    private javax.swing.JLabel jLabelRegBroj;
    private javax.swing.JLabel jLabelSpon;
    private javax.swing.JLabel jLabelTrajanje;
    private javax.swing.JLabel jLabelVrstaAkt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAktivnost;
    private javax.swing.JTable jTableSponzori;
    private javax.swing.JTextField jTextFielDatumOD;
    private javax.swing.JTextField jTextFieldBudzet;
    private javax.swing.JTextField jTextFieldDatumDO;
    private javax.swing.JTextField jTextFieldIznosSponz;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldNazivAkt;
    private javax.swing.JTextField jTextFieldOpisAkt;
    private javax.swing.JTextField jTextFieldOpisProjekta;
    private javax.swing.JTextField jTextFieldRegBr;
    private javax.swing.JTextField jTextFieldTrajanje;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        List<Menadzer> listaMen = new ArrayList<>();
        listaMen = komunikacijaKlijent.Komunikacija.getInstance().vratiListuSviMenadzer();

        for (Menadzer men : listaMen) {
            jComboBoxMenadzer.addItem(men);
        }
        jComboBoxMenadzer.setSelectedItem(null);

        List<Sponzor> listaSponzor = new ArrayList<>();
        listaSponzor = komunikacijaKlijent.Komunikacija.getInstance().vratiListuSviSponzor();

        for (Sponzor sponzor : listaSponzor) {
            jComboBoxSponzor.addItem(sponzor);
        }
        jComboBoxSponzor.setSelectedItem(null);

        List<VrstaAktivnosti> listaVA = new ArrayList<>();
        listaVA = komunikacijaKlijent.Komunikacija.getInstance().ucitajVrstaAktivnosti();

        for (VrstaAktivnosti va:listaVA  ) {
            jComboBoxVAktivnosti.addItem(va);
        }
        jComboBoxVAktivnosti.setSelectedItem(null);

    }

    private void popuniTabeluKreiraj() {

        List<Aktivnost> lista = new ArrayList<>();

        AktivnostModelTabele amt = new AktivnostModelTabele(lista, false);
        jTableAktivnost.setModel(amt);

        List<JeSponzor> listaS = new ArrayList<>();
        JeSponzorModelTabele smt = new JeSponzorModelTabele(listaS);
        jTableSponzori.setModel(smt);

    }

    private void popuniTabeluDetalji() {
        List<JeSponzor> listaS = new ArrayList<>();
        listaS = komunikacijaKlijent.Komunikacija.getInstance().vratiListuJeSponzor(pu);

        JeSponzorModelTabele smt = new JeSponzorModelTabele(listaS);
        jTableSponzori.setModel(smt);

        List<Aktivnost> lista = new ArrayList<>();
        lista = komunikacijaKlijent.Komunikacija.getInstance().vratiListuAktivnost(pu);
       

        AktivnostModelTabele amt = new AktivnostModelTabele(lista, true);
        jTableAktivnost.setModel(amt);

    }

    private boolean validacija(String regBroj, String naziv, String opisProj, String trajanje, String budzet, Menadzer men) {
        boolean regBrReg = regBroj.matches("\\d{4}/20\\d{2}");
        boolean nazivReg = naziv.matches("^[A-Z][a-zA-Z ]*$");
        boolean opisProjReg = !opisProj.isEmpty();
        boolean trajanjeReg = trajanje.matches("[1-9]+[0-9]*");
        boolean budzetReg = budzet.matches("^\\d+(\\.\\d+)?$");
        boolean menReg = men != null;

        if (regBrReg && nazivReg && opisProjReg && trajanjeReg && budzetReg && menReg) {
            return true;
        }

        if (!regBrReg) {
            jTextFieldRegBr.setBorder(new LineBorder(Color.RED, 3));

        }
        if (!nazivReg) {
            jTextFieldNaziv.setBorder(new LineBorder(Color.RED, 3));
        }
        if (!opisProjReg) {
            jTextFieldOpisProjekta.setBorder(new LineBorder(Color.RED, 3));
        }
        if (!trajanjeReg) {
            jTextFieldTrajanje.setBorder(new LineBorder(Color.RED, 3));
        }
        if (!budzetReg) {
            jTextFieldBudzet.setBorder(new LineBorder(Color.RED, 3));
        }
        if (!menReg) {
            jComboBoxMenadzer.setBorder(new LineBorder(Color.RED, 3));
        }

        return false;

    }

    private void sacuvajKreiranje() {

        Projekat ugovor = pokupiPodatkeVratiUgovor();

        if (ugovor == null) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("data_error"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean uspesno = komunikacijaKlijent.Komunikacija.getInstance().kreirajProjektniUgovor(ugovor);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("insert_project_succes"), LanguageManager.getString("success"), JOptionPane.INFORMATION_MESSAGE);
            Cordinator.getInstance().getProjektiFormaController().azurirajTabelu();

        } else {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("insert_project_error"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }

        sacuvajAktivnosti(ugovor);
        sacuvajSponzore(ugovor);

        this.dispose();

    }

    private void sacuvajIzmene() {
        AktivnostModelTabele amt = (AktivnostModelTabele) jTableAktivnost.getModel();
        List<Aktivnost> lista = amt.getLista();
        for (Aktivnost akt : lista) {
            if (!komunikacijaKlijent.Komunikacija.getInstance().promeniAktivnost(akt)) {
                JOptionPane.showMessageDialog(this, LanguageManager.getString("update_project_error"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        JOptionPane.showMessageDialog(this, LanguageManager.getString("update_project_success"), LanguageManager.getString("success"), JOptionPane.INFORMATION_MESSAGE);
    }

    private Projekat pokupiPodatkeVratiUgovor() {
        String regBroj = jTextFieldRegBr.getText().trim();
        String naziv = jTextFieldNaziv.getText();
        String opisProj = jTextFieldOpisProjekta.getText();
        String datumPocetka = jTextFielDatumOD.getText();
        String datumZavrsetka = jTextFieldDatumDO.getText();
        String trajanje = jTextFieldTrajanje.getText();
        String budzet = jTextFieldBudzet.getText();
        Menadzer men = (Menadzer) jComboBoxMenadzer.getSelectedItem();
        Sponzor izv = (Sponzor) jComboBoxSponzor.getSelectedItem();

        if (!validacija(regBroj, naziv, opisProj, trajanje, budzet, men)) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("check_data"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return null;
        }

        int tr = Integer.parseInt(trajanje);
        double budz = Double.parseDouble(budzet);
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        java.util.Date datumOd = null;
        java.util.Date datumDo = null;
        try {
            datumOd = format.parse(datumPocetka);
            datumDo = format.parse(datumZavrsetka);

        } catch (ParseException ex) {
            jTextFielDatumOD.setBorder(new LineBorder(Color.RED, 3));
            jTextFieldDatumDO.setBorder(new LineBorder(Color.RED, 3));
            JOptionPane.showMessageDialog(this, LanguageManager.getString("date_error"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return null;
        }

        Projekat pu = new Projekat(regBroj, naziv, opisProj, budz, tr, datumOd, datumDo, men);
        return pu;

    }

    private void sacuvajAktivnosti(Projekat ugovor) {

        AktivnostModelTabele amt = (AktivnostModelTabele) jTableAktivnost.getModel();
        if (amt.getLista().isEmpty()) {
            return;
        }
        List<Aktivnost> lista = amt.getLista();
        System.out.println(lista.get(0).getNazivAktivnosti());
        for (Aktivnost akt : lista) {
            akt.setProjektniUgovor(ugovor);
            if (!komunikacijaKlijent.Komunikacija.getInstance().kreirajAktivnost(akt)) {
                return;
            }
        }

    }

    private void popuniFormuDetalji() {
        jButtonSacuvaj.setText(LanguageManager.getString("save_changes_button"));
        jButtonObrisiAkt.setVisible(false);
        jButtonDodajAkt.setVisible(false);
        jTextFieldRegBr.setText(pu.getRegBroj() + "");
        jTextFieldNaziv.setText(pu.getNazivProjekta());
        jTextFieldOpisProjekta.setText(pu.getOpisProjekta());
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        jTextFieldDatumDO.setText(format.format(pu.getDatumZavrsetka()));
        jTextFielDatumOD.setText(format.format(pu.getDatumPocetka()));
        jTextFieldTrajanje.setText(pu.getTrajanje() + "");
        jTextFieldBudzet.setText(pu.getBudzet() + "");
        jComboBoxMenadzer.setSelectedItem(pu.getMenadzer());

        jButtonDodajSponzor.setVisible(false);
        jButtonObrisiSponzor.setVisible(false);

        jTextFieldRegBr.setEnabled(false);
        jTextFieldNaziv.setEnabled(false);
        jTextFieldOpisProjekta.setEnabled(false);
        jTextFieldDatumDO.setEnabled(false);
        jTextFielDatumOD.setEnabled(false);
        jTextFieldTrajanje.setEnabled(false);
        jTextFieldBudzet.setEnabled(false);
        jComboBoxMenadzer.setEnabled(false);
        jComboBoxSponzor.setEnabled(false);

        jTextFieldNazivAkt.setEnabled(false);
        jTextFieldOpisAkt.setEnabled(false);
        jComboBoxVAktivnosti.setEnabled(false);

        jTableAktivnost.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(new JCheckBox()));
        jTableSponzori.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(new JCheckBox()));
        jTableSponzori.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(new JCheckBox()));
        jCheckBoxRobni.setEnabled(false);
        jCheckBoxNovcani.setEnabled(false);
        jTextFieldIznosSponz.setEnabled(false);

    }

    private boolean validacijaAktivnosti(String naziv, String opis, VrstaAktivnosti vakt) {
        boolean nazivReg = naziv.matches("^[A-Z][a-zA-Z ]*$");
        boolean opisReg = !opis.isEmpty();
        boolean vaktReg = vakt != null;

        if (nazivReg && opisReg && vaktReg) {
            return true;
        }

        if (!nazivReg) {
            jTextFieldNazivAkt.setBorder(new LineBorder(Color.RED, 3));
        }
        if (!opisReg) {
            jTextFieldOpisAkt.setBorder(new LineBorder(Color.RED, 3));
        }
        if (!vaktReg) {
            jComboBoxVAktivnosti.setBorder(new LineBorder(Color.RED, 3));
        }

        return false;
    }

    private void sacuvajSponzore(Projekat ugovor) {

        JeSponzorModelTabele smt = (JeSponzorModelTabele) jTableSponzori.getModel();
        if (smt.getLista().isEmpty()) {
            return;
        }
        List<JeSponzor> lista = smt.getLista();
        for (JeSponzor s : lista) {
            s.setProjekat(ugovor);
            if (!komunikacijaKlijent.Komunikacija.getInstance().kreirajJeSponzor(s)) {
                return;
            }

        }

    }

    private void listen() {
        jTextFielDatumOD.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

                if (jTextFielDatumOD.getText().equals("dd-mm-yyyy")) {
                    jTextFielDatumOD.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {

                if (jTextFielDatumOD.getText().isEmpty()) {
                    jTextFielDatumOD.setText("dd-mm-yyyy");
                }
            }
        });
        jTextFieldDatumDO.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {

                if (jTextFieldDatumDO.getText().equals("dd-mm-yyyy")) {
                    jTextFieldDatumDO.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {

                if (jTextFieldDatumDO.getText().isEmpty()) {
                    jTextFieldDatumDO.setText("dd-mm-yyyy");
                }
            }
        });
    }

    private void pripremiFormuKreiraj() {

        jComboBoxMenadzer.setEnabled(false);
        kreiranje = true;
        listen();
        setDefaultCloseOperation(ProjektiKreirajForma.DISPOSE_ON_CLOSE);
        jComboBoxMenadzer.setSelectedItem(Cordinator.getInstance().getUlogovani());
        jTableSponzori.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(new JCheckBox()));
        jTableSponzori.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(new JCheckBox()));

    }

    private void azurirajRedneBrojeve() {
        AktivnostModelTabele amt = (AktivnostModelTabele) jTableAktivnost.getModel();
        List<Aktivnost> aktivnosti = amt.getLista();
        for (int i = 0; i < aktivnosti.size(); i++) {
            aktivnosti.get(i).setRedniBroj(i + 1);
        }
    }

    private void setLabels() {
        jLabelBudzet.setText(LanguageManager.getString("budget"));
        jLabelDatPoc.setText(LanguageManager.getString("start_date"));
        jLabelDatZav.setText(LanguageManager.getString("end_date"));
        jLabelIznosSpon.setText(LanguageManager.getString("spons_amount"));
        jLabelMen.setText(LanguageManager.getString("managers"));
        jLabelNazivProj.setText(LanguageManager.getString("project_name"));
        jLabelNazviAkt.setText(LanguageManager.getString("act_name"));
        jLabelOpisAkt.setText(LanguageManager.getString("act_desc"));
        jLabelOpisProj.setText(LanguageManager.getString("proj_desc"));
        jLabelPodaciAkt.setText(LanguageManager.getString("act_data"));
        jLabelPodaciProj.setText(LanguageManager.getString("proj_data"));
        jLabelRegBroj.setText(LanguageManager.getString("reg_num"));
        jLabelSpon.setText(LanguageManager.getString("sponsors"));
        jLabelTrajanje.setText(LanguageManager.getString("duration"));
        jLabelVrstaAkt.setText(LanguageManager.getString("act_type"));

        jButtonDodajAkt.setText(LanguageManager.getString("add_act_button"));
        jButtonDodajSponzor.setText(LanguageManager.getString("add_spons_button"));
        jButtonNazad.setText(LanguageManager.getString("back_button"));
        jButtonObrisiAkt.setText(LanguageManager.getString("delete_act_button"));
        jButtonObrisiSponzor.setText(LanguageManager.getString("delete_spons_button"));
        jButtonSacuvaj.setText(LanguageManager.getString("save_button"));

    }

}
