/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import condinator.Cordinator;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import language.LanguageManager;
import model.Sponzor;
import model.Mesto;

/**
 *
 * @author Korisnik
 */
public class SponzorKreirajDetaljiForma extends javax.swing.JDialog {

    SponzorForma roditelj;
    Sponzor sponzor;

    public Sponzor getSponzor() {
        return sponzor;
    }

    public JComboBox<Mesto> getjComboBoxMesto() {
        return jComboBoxMesto;
    }

    /**
     * Creates new form IzvodjacKreirajDetaljiForma
     */
    public SponzorKreirajDetaljiForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLabels();
        setTitle(LanguageManager.getString("create_sponsor_title"));
        pripremiFormuKreiraj();
        popuniComboBox();
        roditelj = (SponzorForma) parent;

    }

    public SponzorKreirajDetaljiForma(java.awt.Frame parent, boolean modal, Sponzor sponzor) {
        super(parent, modal);
        initComponents();
        setLabels();
        popuniComboBox();
        setTitle(LanguageManager.getString("update_sponsor_title"));
        roditelj = (SponzorForma) parent;
        this.sponzor = sponzor;
        System.out.println(sponzor.getMesto());
        pripremiFormuDetalji();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPodaci = new javax.swing.JLabel();
        jLabelMatBr = new javax.swing.JLabel();
        jLabelNazivFirme = new javax.swing.JLabel();
        jLabelVlasnik = new javax.swing.JLabel();
        jLabelMesto = new javax.swing.JLabel();
        jTextFieldMBroj = new javax.swing.JTextField();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldVlasnik = new javax.swing.JTextField();
        jComboBoxMesto = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPodaci.setText("Podaci o izvodjacu");

        jLabelMatBr.setText("Maticni broj");

        jLabelNazivFirme.setText("Naziv firme");

        jLabelVlasnik.setText("Vlasnik");

        jLabelMesto.setText("Mesto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabelPodaci)
                        .addGap(0, 176, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatBr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNazivFirme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelVlasnik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldMBroj)
                            .addComponent(jTextFieldNaziv)
                            .addComponent(jTextFieldVlasnik)
                            .addComponent(jComboBoxMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelPodaci)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMatBr)
                    .addComponent(jTextFieldMBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNazivFirme)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVlasnik)
                    .addComponent(jTextFieldVlasnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMesto)
                    .addComponent(jComboBoxMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        jButtonNazad.setText("Nazad");
        jButtonNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonKreiraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNazad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButtonNazad)
                .addGap(49, 49, 49)
                .addComponent(jButtonIzmeni)
                .addGap(39, 39, 39)
                .addComponent(jButtonSacuvaj)
                .addGap(46, 46, 46)
                .addComponent(jButtonObrisi)
                .addGap(43, 43, 43)
                .addComponent(jButtonKreiraj)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        String matBr = jTextFieldMBroj.getText();
        String naziv = jTextFieldNaziv.getText();
        String vlasnik = jTextFieldVlasnik.getText();
        Mesto mesto = (Mesto) jComboBoxMesto.getSelectedItem();

        if (!validacija(matBr, naziv, vlasnik, mesto)) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("check_data"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        Sponzor sponzor = new Sponzor(matBr, naziv, vlasnik, false, mesto);
        boolean uspesno = komunikacijaKlijent.Komunikacija.getInstance().kreirajSponzor(sponzor);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("create_sponsor_success"), LanguageManager.getString("success"), JOptionPane.INFORMATION_MESSAGE);
            Cordinator.getInstance().getsponzorFormaController().azurirajTabelu();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("create_sponsor_error"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed

        jTextFieldNaziv.setEnabled(true);
        jTextFieldVlasnik.setEnabled(true);

        jButtonSacuvaj.setEnabled(true);
        jButtonObrisi.setEnabled(false);


    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        String matBr = jTextFieldMBroj.getText();
        String naziv = jTextFieldNaziv.getText();
        String vlasnik = jTextFieldVlasnik.getText();
        Mesto mesto = (Mesto) jComboBoxMesto.getSelectedItem();

        if (!validacija(matBr, naziv, vlasnik, mesto)) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("check_data"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        Sponzor sponzor = new Sponzor(matBr, naziv, vlasnik, false, mesto);
        boolean uspesno = komunikacijaKlijent.Komunikacija.getInstance().promeniSponzor(sponzor);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("update_sponsor_success"), LanguageManager.getString("success"), JOptionPane.INFORMATION_MESSAGE);
            Cordinator.getInstance().getsponzorFormaController().azurirajTabelu();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("update_sponsor_error"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int odgovor = JOptionPane.showConfirmDialog(this, LanguageManager.getString("delete_sponsor_question"), LanguageManager.getString("confirmation"), JOptionPane.YES_NO_OPTION);
        if (odgovor != JOptionPane.YES_OPTION) {
            return;
        }
        sponzor.setObrisan(true);
        boolean uspesno = komunikacijaKlijent.Komunikacija.getInstance().obrisiSponzor(sponzor);

        if (uspesno) {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("delete_sponsor_success"), LanguageManager.getString("success"), JOptionPane.INFORMATION_MESSAGE);
            Cordinator.getInstance().getsponzorFormaController().azurirajTabelu();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, LanguageManager.getString("delete_sponsor_error"), LanguageManager.getString("error"), JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonNazadActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SponzorKreirajDetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SponzorKreirajDetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SponzorKreirajDetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SponzorKreirajDetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SponzorKreirajDetaljiForma dialog = new SponzorKreirajDetaljiForma(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonNazad;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<Mesto> jComboBoxMesto;
    private javax.swing.JLabel jLabelMatBr;
    private javax.swing.JLabel jLabelMesto;
    private javax.swing.JLabel jLabelNazivFirme;
    private javax.swing.JLabel jLabelPodaci;
    private javax.swing.JLabel jLabelVlasnik;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldMBroj;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldVlasnik;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormuKreiraj() {
        jButtonIzmeni.setVisible(false);
        jButtonObrisi.setVisible(false);
        jButtonSacuvaj.setVisible(false);
    }

    private boolean validacija(String matBr, String naziv, String vlasnik, Mesto mesto) {

        boolean matReg = matBr.matches("^\\d{8}$");
        boolean nazivReg = naziv.matches("^[A-Z][a-zA-Z ]*$");
        boolean vlasniReg = vlasnik.matches("^[A-Z][a-zA-Z ]*$");
        boolean mestoReg = mesto != null;
        if (matReg && nazivReg && vlasniReg && mestoReg) {
            return true;
        }

        if (!matReg) {
            jTextFieldMBroj.setBorder(new LineBorder(Color.RED, 3));

        }
        if (!nazivReg) {
            jTextFieldNaziv.setBorder(new LineBorder(Color.RED, 3));
        }

        if (!vlasniReg) {
            jTextFieldVlasnik.setBorder(new LineBorder(Color.RED, 3));
        }
        if (!mestoReg) {
            jComboBoxMesto.setBorder(new LineBorder(Color.RED, 3));
        }

        return false;
    }

    private void popuniComboBox() {
        List<Mesto> lista = komunikacijaKlijent.Komunikacija.getInstance().vratiListuSviMesto();
        for (Mesto mesto : lista) {
            jComboBoxMesto.addItem(mesto);
        }
    }

    private void pripremiFormuDetalji() {
        jButtonKreiraj.setVisible(false);
        jTextFieldNaziv.setEnabled(false);
        jTextFieldVlasnik.setEnabled(false);
        jComboBoxMesto.setEnabled(false);
        jTextFieldMBroj.setEnabled(false);
        jButtonSacuvaj.setEnabled(false);

        jTextFieldMBroj.setText(sponzor.getMaticniBroj());
        jTextFieldNaziv.setText(sponzor.getNazivFirme());
        jTextFieldVlasnik.setText(sponzor.getVlasnik());
        jComboBoxMesto.setSelectedItem(sponzor.getMesto());

    }

    private void setLabels() {
        jLabelMatBr.setText(LanguageManager.getString("rnc"));
        jLabelMesto.setText(LanguageManager.getString("city"));
        jLabelNazivFirme.setText(LanguageManager.getString("company_name"));
        jLabelPodaci.setText(LanguageManager.getString("data"));
        jLabelVlasnik.setText(LanguageManager.getString("owner"));
        
        
        jButtonIzmeni.setText(LanguageManager.getString("update_button"));
        jButtonKreiraj.setText(LanguageManager.getString("create_button"));
        jButtonNazad.setText(LanguageManager.getString("back_button"));
        jButtonObrisi.setText(LanguageManager.getString("delete_button"));
        jButtonSacuvaj.setText(LanguageManager.getString("save_changes_button"));
        
    }

}
