/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;


import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import model.Sponzor;
import model.Mesto;

/**
 *
 * @author Korisnik
 */
public class SponzorKreirajDetaljiForma extends javax.swing.JDialog {

    SponzorForma roditelj;
    Sponzor izvodjac;

    /**
     * Creates new form IzvodjacKreirajDetaljiForma
     */
    public SponzorKreirajDetaljiForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Kreiraj sponzora");
        pripremiFormuKreiraj();
        popuniComboBox();
        roditelj = (SponzorForma) parent;

    }

    public SponzorKreirajDetaljiForma(java.awt.Frame parent, boolean modal, Sponzor izvodjac) {
        super(parent, modal);
        initComponents();
        popuniComboBox();
        setTitle("Detalji sponzora");
        roditelj = (SponzorForma) parent;
        this.izvodjac = izvodjac;
        pripremiFormuDetalji();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMBroj = new javax.swing.JTextField();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldVlasnik = new javax.swing.JTextField();
        jComboBoxMesto = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonKreiraj = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Podaci o izvodjacu");

        jLabel2.setText("Maticni broj");

        jLabel3.setText("Naziv firme");

        jLabel4.setText("Vlasnik");

        jLabel5.setText("Mesto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxMesto, 0, 95, Short.MAX_VALUE)
                            .addComponent(jTextFieldVlasnik, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jTextFieldNaziv)
                            .addComponent(jTextFieldMBroj))))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldVlasnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonSacuvaj.setText("Sacuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        jButton1.setText("Nazad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonKreiraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jButtonIzmeni)
                .addGap(39, 39, 39)
                .addComponent(jButtonSacuvaj)
                .addGap(46, 46, 46)
                .addComponent(jButtonObrisi)
                .addGap(43, 43, 43)
                .addComponent(jButtonKreiraj)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
//        String matBr = jTextFieldMBroj.getText();
//        String naziv = jTextFieldNaziv.getText();
//        String vlasnik = jTextFieldVlasnik.getText();
//        Mesto mesto = (Mesto) jComboBoxMesto.getSelectedItem();
//
//        if (!validacija(matBr, naziv, vlasnik, mesto)) {
//            JOptionPane.showMessageDialog(this, "Proverite unesene podatke", "Upozorenje", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        Sponzor gi = new Sponzor(matBr, naziv, vlasnik, false, mesto);
//        boolean uspesno = Controller.getInstance().kreirajSponzor(gi);
//        if (uspesno) {
//            JOptionPane.showMessageDialog(this, "Sponzor je uspesno kreiran", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
//            roditelj.popuniTabelu();
//        } else {
//            JOptionPane.showMessageDialog(this, "Sponzor nije uspesno kreiran", "Greska", JOptionPane.ERROR_MESSAGE);
//        }
//
//        jTextFieldMBroj.setText("");
//        jTextFieldNaziv.setText("");
//        jTextFieldVlasnik.setText("");
//        jComboBoxMesto.setSelectedItem(null);
    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed

        jTextFieldNaziv.setEnabled(true);
        jTextFieldVlasnik.setEnabled(true);

        jButtonSacuvaj.setEnabled(true);
        jButtonObrisi.setEnabled(false);


    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
//        String matBr = jTextFieldMBroj.getText();
//        String naziv = jTextFieldNaziv.getText();
//        String vlasnik = jTextFieldVlasnik.getText();
//        Mesto mesto = (Mesto) jComboBoxMesto.getSelectedItem();
//
//        if (!validacija(matBr, naziv, vlasnik, mesto)) {
//            JOptionPane.showMessageDialog(this, "Proverite unesene podatke", "Upozorenje", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//        Sponzor gi = new Sponzor(matBr, naziv, vlasnik, false, mesto);
//        boolean uspesno = Controller.getInstance().promeniSponzor(gi);
//        if (uspesno) {
//            JOptionPane.showMessageDialog(this, "Sponzor je uspesno izmenjen", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
//            roditelj.popuniTabelu();
//        } else {
//            JOptionPane.showMessageDialog(this, "Sponzor nije uspesno izmenjen", "Greska", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
//        int odgovor = JOptionPane.showConfirmDialog(this, "Da li zelite da obrisete sponzora?", "Potvrda", JOptionPane.YES_NO_OPTION);
//        if (odgovor != JOptionPane.YES_OPTION) {
//            return;
//        }
//        izvodjac.setObrisan(true);
//        boolean uspesno = Controller.getInstance().obrisiSponzor(izvodjac);
//        if (uspesno) {
//            JOptionPane.showMessageDialog(this, "Sponzor je uspesno obrisan", "Uspesno", JOptionPane.INFORMATION_MESSAGE);
//            roditelj.popuniTabelu();
//            this.dispose();
//        } else {
//            JOptionPane.showMessageDialog(this, "Sponzor nije uspesno obrisan", "Greska", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SponzorKreirajDetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SponzorKreirajDetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SponzorKreirajDetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SponzorKreirajDetaljiForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SponzorKreirajDetaljiForma dialog = new SponzorKreirajDetaljiForma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JComboBox<Mesto> jComboBoxMesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldMBroj;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldVlasnik;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormuKreiraj() {
        jButtonIzmeni.setVisible(false);
        jButtonObrisi.setVisible(false);
        jButtonSacuvaj.setVisible(false);
    }

    private boolean validacija(String matBr, String naziv, String vlasnik, Mesto mesto) {

        boolean matReg = matBr.matches("^\\d{8}$");
        boolean nazivReg = naziv.matches("^[A-Z][a-zA-Z ]*$");
        boolean vlasniReg = vlasnik.matches("^[A-Z][a-zA-Z ]*$");
        boolean mestoReg = mesto != null;
        if (matReg && nazivReg && vlasniReg && mestoReg) {
            return true;
        }

        if (!matReg) {
            jTextFieldMBroj.setBorder(new LineBorder(Color.RED, 3));

        }
        if (!nazivReg) {
            jTextFieldNaziv.setBorder(new LineBorder(Color.RED, 3));
        }

        if (!vlasniReg) {
            jTextFieldVlasnik.setBorder(new LineBorder(Color.RED, 3));
        }
        if (!mestoReg) {
            jComboBoxMesto.setBorder(new LineBorder(Color.RED, 3));
        }

        return false;
    }

    private void popuniComboBox() {
//        List<Mesto> lista = new ArrayList<>();
//        boolean uspesno = Controller.getInstance().vratiListuSviMesto(lista);
//        if (uspesno) {
//            for (Mesto mesto : lista) {
//                jComboBoxMesto.addItem(mesto);
//            }
//
//        } else {
//            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita listu mesta", "Greska", JOptionPane.ERROR_MESSAGE);
//        }
    }

    private void pripremiFormuDetalji() {
        jButtonKreiraj.setVisible(false);
        jTextFieldNaziv.setEnabled(false);
        jTextFieldVlasnik.setEnabled(false);
        jComboBoxMesto.setEnabled(false);
        jTextFieldMBroj.setEnabled(false);
        jButtonSacuvaj.setEnabled(false);

        jTextFieldMBroj.setText(izvodjac.getMaticniBroj());
        jTextFieldNaziv.setText(izvodjac.getNazivFirme());
        jTextFieldVlasnik.setText(izvodjac.getVlasnik());
        jComboBoxMesto.setSelectedItem(izvodjac.getMesto());
    }
}
